-- Stream keys, one secret per (stream, purpose). Hot-reloaded by config.lua.
--
--   <app>/<stream>|play     viewing side. This one is embedded in the player
--                           pages (deploy/nginx/html/rtcplayer.html), so treat
--                           it as public: it must never authorize ingest.
--   <app>/<stream>|publish  ingest side (RTMP on_publish, WHIP). Server-side
--                           only; no page or client script ships it.
--
-- The signed message is identical for both roles -- "<app>/<stream>|t=<t>" --
-- and the separation comes entirely from the secrets. That is deliberate: with
-- one shared secret every viewer was a potential publisher, because whoever can
-- load the player page can mint any token that secret verifies. Two secrets
-- mean a play token simply fails publish verification.
--
-- Keys are written out literally rather than generated by a helper. The tools
-- that read this file (run.sh, scripts/e2e-*.sh) parse it as text, because the
-- scripts have no Lua interpreter; a generated key is invisible to them.
--
-- The demo uses one play secret and one publish secret across all live/*
-- streams. Production should give each stream its own pair.

return {
    ["live/livestream|play"]       = "demo-secret-0123456789abcdef0123456789abcdef",
    ["live/livestream|publish"]    = "push-secret-9f8e7d6c5b4a39281706f5e4d3c2b1a0",

    -- Multi-resolution ladder (transcoded from live/livestream by run.sh transcode).
    ["live/livestream_1080p|play"]    = "demo-secret-0123456789abcdef0123456789abcdef",
    ["live/livestream_1080p|publish"] = "push-secret-9f8e7d6c5b4a39281706f5e4d3c2b1a0",
    ["live/livestream_720p|play"]     = "demo-secret-0123456789abcdef0123456789abcdef",
    ["live/livestream_720p|publish"]  = "push-secret-9f8e7d6c5b4a39281706f5e4d3c2b1a0",
    ["live/livestream_540p|play"]     = "demo-secret-0123456789abcdef0123456789abcdef",
    ["live/livestream_540p|publish"]  = "push-secret-9f8e7d6c5b4a39281706f5e4d3c2b1a0",
    ["live/livestream_360p|play"]     = "demo-secret-0123456789abcdef0123456789abcdef",
    ["live/livestream_360p|publish"]  = "push-secret-9f8e7d6c5b4a39281706f5e4d3c2b1a0",

    ["live/whiptest|play"]    = "demo-secret-0123456789abcdef0123456789abcdef",
    ["live/whiptest|publish"] = "push-secret-9f8e7d6c5b4a39281706f5e4d3c2b1a0",

    -- Reserved for scripts/e2e-play-json.sh so the two e2e guards never contend
    -- for the same name (a claimed name would make the other one's publish fail).
    ["live/playjson|play"]    = "demo-secret-0123456789abcdef0123456789abcdef",
    ["live/playjson|publish"] = "push-secret-9f8e7d6c5b4a39281706f5e4d3c2b1a0",

    -- Streams whose whole point is a distinct credential: their own pair, so a
    -- test that leaks one cannot touch the demo streams.
    ["live/test|play"]       = "test-secret-4567890abcdef0123456789abcdef",
    ["live/test|publish"]    = "test-push-8a7b6c5d4e3f20192837465af1b2c3d4",

    ["live/hotreload|play"]  = "hot-secret-67890abcdef0123456789abcdef0",
    ["live/hotreload|publish"] = "hot-push-1a2b3c4d5e6f7081928374655a4b3c2d",

    ["live/luahotload|play"] = "lua-secret-abcdef0123456789abcdef012345",
    ["live/luahotload|publish"] = "lua-push-0f1e2d3c4b5a69788796a5b4c3d2e1f0",
}
